return {
    "nvim-treesitter/nvim-treesitter",
    lazy = false,
    build = ":TSUpdate",
    opts = {
        ensure_installed = {
            "html",
            "css",
            "javascript",
            "typescript",
            "tsx",
            "json",
            "graphql",
            "vue",
            "lua",
            "python",
            "rust",
            "c",
            "cpp",
            "go",
            "java",
            "bash",
            "toml",
            "yaml",
            "markdown",
            "markdown_inline",
            "sql",
            "regex",
        },
        highlight = { enable = true },
        indent = { enable = true },
        auto_install = true,
    },
}
